name: checkstyle

on: [push, pull_request]

jobs:
  java-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Java Checkstyle
        uses: Justintime50/java-checkstyle-action@v1
        with:
          style_suite: google
          # The directory to run Checkstyle recursively on
          # (default is the repo root)
          # directory: src
